name = "kongo-site"
pages_build_output_dir = ".pages-output"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://gapcihekbovyioiamqmf.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_OWIfb4iSl-zY1J4eav39Fg_-33GCDxm"
